# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hpqc.communication.v1 import quantum_pb2 as hpqc_dot_communication_dot_v1_dot_quantum__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hpqc/communication/v1/quantum_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuantumServiceStub(object):
    """Minimal, versioned contract between an HPC application and a QC server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/hpqc.communication.v1.QuantumService/Invoke',
                request_serializer=hpqc_dot_communication_dot_v1_dot_quantum__pb2.QuantumRequest.SerializeToString,
                response_deserializer=hpqc_dot_communication_dot_v1_dot_quantum__pb2.QuantumResponse.FromString,
                _registered_method=True)


class QuantumServiceServicer(object):
    """Minimal, versioned contract between an HPC application and a QC server.
    """

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantumServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=hpqc_dot_communication_dot_v1_dot_quantum__pb2.QuantumRequest.FromString,
                    response_serializer=hpqc_dot_communication_dot_v1_dot_quantum__pb2.QuantumResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hpqc.communication.v1.QuantumService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hpqc.communication.v1.QuantumService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuantumService(object):
    """Minimal, versioned contract between an HPC application and a QC server.
    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hpqc.communication.v1.QuantumService/Invoke',
            hpqc_dot_communication_dot_v1_dot_quantum__pb2.QuantumRequest.SerializeToString,
            hpqc_dot_communication_dot_v1_dot_quantum__pb2.QuantumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
