# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hpqc/communication/v1/quantum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hpqc/communication/v1/quantum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#hpqc/communication/v1/quantum.proto\x12\x15hpqc.communication.v1\"J\n\x0eQuantumRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x12\n\ninput_json\x18\x02 \x01(\t\x12\r\n\x05shots\x18\x03 \x01(\r\"7\n\x0fQuantumResponse\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x02 \x01(\t2i\n\x0eQuantumService\x12W\n\x06Invoke\x12%.hpqc.communication.v1.QuantumRequest\x1a&.hpqc.communication.v1.QuantumResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hpqc.communication.v1.quantum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUANTUMREQUEST']._serialized_start=62
  _globals['_QUANTUMREQUEST']._serialized_end=136
  _globals['_QUANTUMRESPONSE']._serialized_start=138
  _globals['_QUANTUMRESPONSE']._serialized_end=193
  _globals['_QUANTUMSERVICE']._serialized_start=195
  _globals['_QUANTUMSERVICE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
